name: Build on Linux and Windows

on:
  push:
  pull_request:

jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies (build-essential, cmake)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .

  build-windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
